################################################################################
## Job submission arguments
################################################################################

analysis_executable_parser=bilby_antiglitch.bilby_pipe.create_parser

################################################################################
## Glitch waveform arguments
################################################################################

glitch-frequency-domain-source-model = bilby_antiglitch.source.antiglitch
detectors-glitch = ['L1']

################################################################################
## Likelihood arguments
################################################################################

likelihood-type=GravitationalWaveTransientPlusGlitch

################################################################################
## Injection arguments
################################################################################

injection-glitch-frequency-domain-source-model = bilby_antiglitch.source.antiglitch
